 variable "region" {}
 variable "main_vpc_cidr" {}
 variable "public_subnet1" {}
 variable "public_subnet2" {}
 variable "private_subnet1" {}
 variable "private_subnet2" {}
 variable "zone1" {}
 variable "zone2" {}
 variable "inst_type" {}
 variable "key" {}